### ISSUE TITLE
Infusion not working

### ISSUE THREAD

**Issue by Danymaddox** [TheDrunkMafia/ThaumicInfusion#54] opened 2016-01-14 16:12 UTC
Hi!
I'm using the lastest version of Thaumic infusion with Thaumcraft 5.1.3 but when I try to infuse any block the infusion does not work. I mean, the block is infused but it isn't working. I've tried with all aspects but no one works. The forge version is 11.15.0.1696. Also I've tried in creative mode and in survival mode.

Thanks!

**Comment by TheDrunkMafia** [comment] 2016-01-14 17:06
Can you record what you are doing to make it easier for me to see?

**Comment by TheDrunkMafia** [comment] 2016-01-14 18:43
Also are you able to go into you mc instance folder and upload the Ti_transformer.log please.

**Comment by Danymaddox** [comment] 2016-01-14 19:11
Yes, here you have the video: https://www.youtube.com/watch?v=_S_WvPUZxsM
And here the .log: https://mega.nz/#!8MY2wSob!OIhaJYEjTXyP-FtRtfMLfnj3PJLYLjFMMWH1Qi5yI9I

Hope this can help you ^^

**Comment by TheDrunkMafia** [comment] 2016-01-14 20:39
The video is private, however I now know what the cause is. The Log file has shown that the transformer is for some reason not picking up any other block classes while loading, although it is finding super classes. What mods do you have in the instance and can you also please post the FML log as well?

**Comment by TheDrunkMafia** [comment] 2016-01-14 21:25
Nevermind, I've figured out the issue. It is a large blunder on my part, I forgot to update the class names from 1.8 to 1.8.9's SRG. All is fixed now and I am waiting on curse to accept the new build.

**Closed by TheDrunkMafia** 2016-01-14 21:25 UTC
