### ISSUE TITLE
Performance Issue [4.02]

### ISSUE THREAD

**Issue by Mitchellbrine** [TheDrunkMafia/ThaumicInfusion#25] opened 2015-05-25 02:39 UTC
Noticed with the latest version of the mod that there are performance issues involving ram usage. When run through a sampler, we got this result:

![](http://i.imgur.com/33Rov9l.png)

This is on the client thread, not the server thread, so the client is feeling the pain, not the server.

**Comment by TheDrunkMafia** [comment] 2015-05-25 13:10
This has already been fixed in my dev environment, the cause of the performance drop is due the way that version looks up data stored, the new version uses my own list which removes the lookup time completely. I will be updating it soon.

**Comment by TheDrunkMafia** [comment] 2015-06-04 11:18
It's finally been fixed, this list will remove the look up time that is causing the performance to drop. I've been working on this class for the last month and it's finally been implemented into my data strucuture and its good to go.

https://github.com/TheDrunkMafia/ThaumicInfusion/blob/master/src/main/java/drunkmafia/thaumicinfusion/common/util/Coordinate2List.java

**Closed** 2015-06-08 21:52 UTC
